language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -e .[test]
script:
- python setup.py check -rms
- flake8
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  skip_existing: true
  on:
    tags: true
    branch: master
  user: __token__
  password:
    secure: MsrCHNwegKWlIWOsG//lvUrZGyZvVTgtcwFgGBKPNLwihPhwikuOY03T+CKbvBAvssHOemvihEbCECUam9e7L5ot2qo/HLPSr245GWgpYA+D/Fy5iqUMT5EAUHju8lycM2ZqUVShNYV08TqwojDNywcLExT9oGWIiQwS9zJxiDsfqhVLsxdN9+muJCYNkaBeShFpoEz27F9nyIs5/AlrnLgN2WxylkGKtR03VrAm5nbpESCIdAFpIwbCUrZmBbyXrikF5Rfe/V/RUI5LqVzP7JgQrgo8fjfT2TdZndtB3gEFwG9aiZwZe+Cz+Nb6424yE7bxh/i08z517b3bjecybtHpWx3E2UxXCqay2GD0RA7eD11O+NVE6BjyknuP1hJSeKDpgZhiSb1lMEfTds3Jrz2/ofcC08Ms53+S4j5pq7tbkK0xgyhjURlZxCR4LovKsxSl3Oq14pIg0NNB0ki2aKlz2UblT0KxEfwmGJA9x4uePb9gv3YulXXv7yniUKarSujGFMBXAgp9hSOyOSeuUh+J1U1xEsSDuHPIUDez0e9UUKoYE4MQgQeu8iP9DvR1sgn1XpYX5Z/4vchxi3dGA6PCH4FPa8jReGczXQnEExkusmZs7V5fmubApsaoRB7T1j1Rq3fSKIs6ha2O+q4T8lRNxTbYGlFEZUkiSyA31vk=
